server:
  port: 8080
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
spring:
  application.name: organic-bazaar-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery.locator.enabled: true
      routes:
        - id: product-reviews
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/*/reviews/**
          filters:
            - AuthFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates: Path=/users/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates: Path=/products/**
        - id: order-service
          uri: lb://ORDERS-SERVICE
          predicates: Path=/orders/**
          filters:
            - AuthFilter
        - id: subscription-service
          uri: lb://ORDERS-SERVICE
          predicates: Path=/subscriptions/**
          filters:
            - AuthFilter
