########################################################
########### ORGANIC BAAZAAR API TEST ###################
########################################################
@host = localhost
@port = 8080
@url = http://{{host}}:{{port}}
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXRpbkAxMjMuY29tIiwiaWF0IjoxNzI2NTU1MjE4fQ.6rUQeP3sgkSQmKx081PMLKtPI30DPI-4PLIEtYTZViU


# ==== Products ========================================
@port = 8083
@url = http://{{host}}:{{port}}

### get all Products
GET {{url}}/products?category=Fruit&sort=price&order=-1

### get product by id
GET {{url}}/1

### get product by ids
GET {{url}}/ids?ids=1&ids=2&ids=3

### create new product
POST {{url}}

{
    "name": "Broccoli", "category": "Vegetable", "price": 0.80, "stock": 180
}

### update product

### delete product

### bulk add products
POST {{url}}/add-many

[
    {"name": "Apple", "category": "Fruit", "price": 1.00, "stock": 100},
    {"name": "Banana", "category": "Fruit", "price": 0.50, "stock": 150},
    {"name": "Carrot", "category": "Vegetable", "price": 0.30, "stock": 200},
    {"name": "Broccoli", "category": "Vegetable", "price": 0.80, "stock": 180},
    {"name": "Chicken Breast", "category": "Meat", "price": 5.00, "stock": 50},
    {"name": "Salmon", "category": "Fish", "price": 6.00, "stock": 60},
    {"name": "Milk", "category": "Dairy", "price": 1.20, "stock": 120},
    {"name": "Cheese", "category": "Dairy", "price": 2.50, "stock": 80},
    {"name": "Bread", "category": "Bakery", "price": 1.00, "stock": 150},
    {"name": "Butter", "category": "Dairy", "price": 1.80, "stock": 70},
    {"name": "Orange", "category": "Fruit", "price": 1.20, "stock": 130},
    {"name": "Strawberry", "category": "Fruit", "price": 2.00, "stock": 90},
    {"name": "Eggs", "category": "Dairy", "price": 2.50, "stock": 100},
    {"name": "Rice", "category": "Grain", "price": 3.00, "stock": 200},
    {"name": "Pasta", "category": "Grain", "price": 1.50, "stock": 180},
    {"name": "Olive Oil", "category": "Condiment", "price": 5.50, "stock": 50},
    {"name": "Tomato Sauce", "category": "Condiment", "price": 1.80, "stock": 60},
    {"name": "Yogurt", "category": "Dairy", "price": 1.00, "stock": 110},
    {"name": "Granola", "category": "Snack", "price": 3.00, "stock": 90},
    {"name": "Nuts", "category": "Snack", "price": 4.00, "stock": 70},
    {"name": "Chocolate", "category": "Snack", "price": 2.20, "stock": 100}
]

### Add reviews to product
POST {{url}}/1/reviews
userId: 2

{
  "comment": "Bit overpriced",
  "rating": 3
}

### Delete review
DELETE {{url}}/1/reviews/2
userId: 2


### ==== Auth ============================================
@port = 8082
@url = http://{{host}}:{{port}}

### get all users
GET {{url}}

### register
POST {{url}}/register

{
    "name": "Kumar Jatin",
    "email": "jatin@123.com",
    "password": "jatin",
    "address": "New delhi",
    "phoneNumber": "98239234"
}

### login
GET http://localhost:8080/products/1
Authorization: Bearer {{token}}

### login
POST http://localhost:8080/users/login

{
    "email": "jatin@123.com",
    "password": "jatin"
}


### very-token
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXRpbkAxMjkkkkkkkkkkkkMuY29tIiwiaWF0IjoxNzI2NTUwNzA2LCJleHAiOjE3MjY1NTA4MTR9.6_otfKpaeQ-84NOX89qAklBydLML_mBt3a_Il31i76M
GET {{url}}/verify-token?token={{token}}


# ==== Orders ==========================================
@port = 8085
@url = http://{{host}}:{{port}}

### get all orders
GET {{url}}

### create order
POST {{url}}
userId: 2

{
    "userId": 2,
    "orderItems": [
        {
            "productId": 2,
            "quantity": 4
        },
        {
            "productId": 1,
            "quantity": 3
        }
    ]
}

### Get all subscriptions
GET {{url}}/subscriptions
userId : 2

### create new subscription
POST {{url}}/subscriptions
userId: 2

{
    "productId": 2,
    "quantity": 10,
    "scheduleType": "WEEKLY",
    "deliveryDays": [
    "MONDAY",
    "FRIDAY"
    ]
}

### change subscription status
PATCH {{url}}/subscriptions/1/status
userId: 2

{
    "status": "PAUSED"
}
