########################################################
########### ORGANIC BAAZAAR API TEST ###################
########################################################
@host = localhost
@port = 8080
@url = http://{{host}}:{{port}}
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXRpbkAxMjMuY29tIiwiaWF0IjoxNzI2NTU1MjE4fQ.6rUQeP3sgkSQmKx081PMLKtPI30DPI-4PLIEtYTZViU


# ==== Products ========================================
@port = 8083
@url = http://{{host}}:{{port}}

### get all Products
GET {{url}}/products?category=Fruit&sort=price&order=-1

### get product by id
GET {{url}}/1

### get product by ids
GET {{url}}/ids?ids=1&ids=2&ids=3

### create new product
POST {{url}}

{
    "name": "Broccoli", "category": "Vegetable", "price": 0.80, "stock": 180
}

### update product

### delete product

### bulk add products
POST {{url}}/products/add-many

[
  {
    "name": "Apple",
    "description": "Fresh and juicy red apples.",
    "image": "apple.jpg",
    "category": "Fruits",
    "price": 3.50,
    "stock": 150
  },
  {
    "name": "Banana",
    "description": "Ripe and sweet bananas.",
    "image": "banana.jpg",
    "category": "Fruits",
    "price": 1.20,
    "stock": 200
  },
  {
    "name": "Guava",
    "description": "Organic crunchy guava.",
    "image": "guava.jpg",
    "category": "Fruits",
    "price": 2.00,
    "stock": 100
  },
  {
    "name": "Golden apple",
    "description": "It's basically an apple but golden",
    "image": "golden-apple.jpg",
    "category": "Fruits",
    "price": 2.50,
    "stock": 75
  },
  {
    "name": "Coconut",
    "description": "Tough on the outside but soft in the inside.",
    "image": "coconut.jpg",
    "category": "Vegetables",
    "price": 2.20,
    "stock": 120
  },
  {
    "name": "Dragon Fruit",
    "description": "It's sweet, it's exotic, it's tasty.",
    "image": "dragon-fruits.webp",
    "category": "Fruits",
    "price": 9.00,
    "stock": 180
  },
  {
    "name": "Whole wheat bread",
    "description": "Freshly baked from the oven",
    "image": "whole-wheat-bread.jpg",
    "category": "Bakery",
    "price": 1.80,
    "stock": 90
  },
  {
    "name": "Pineapple",
    "description": "Fresh and sweet pineapple.",
    "image": "pineapple.webp",
    "category": "Fruits",
    "price": 4.00,
    "stock": 60
  },
  {
    "name": "Sourdough",
    "description": "It's not sour",
    "image": "sourdough.jpg",
    "category": "Bakery",
    "price": 3.80,
    "stock": 130
  },
  {
    "name": "Burger Bun",
    "description": "Freshly baked soft buns",
    "image": "burger-bun.jpg",
    "category": "Bakery",
    "price": 1.80,
    "stock": 160
  }
]

### Add reviews to product
POST {{url}}/1/reviews
userId: 2

{
  "comment": "Bit overpriced",
  "rating": 3
}

### Delete review
DELETE {{url}}/1/reviews/2
userId: 2


### ==== Auth ============================================
@port = 8082
@url = http://{{host}}:{{port}}

### get all users
GET {{url}}

### register
POST {{url}}/register

{
    "name": "Kumar Jatin",
    "email": "jatin@123.com",
    "password": "jatin",
    "address": "New delhi",
    "phoneNumber": "98239234"
}

### login
GET http://localhost:8080/products/1
Authorization: Bearer {{token}}

### login
POST http://localhost:8080/users/login

{
    "email": "jatin@123.com",
    "password": "jatin"
}


### very-token
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXRpbkAxMjkkkkkkkkkkkkMuY29tIiwiaWF0IjoxNzI2NTUwNzA2LCJleHAiOjE3MjY1NTA4MTR9.6_otfKpaeQ-84NOX89qAklBydLML_mBt3a_Il31i76M
GET {{url}}/verify-token?token={{token}}


# ==== Orders ==========================================
@port = 8085
@url = http://{{host}}:{{port}}

### get all orders
GET {{url}}

### create order
POST {{url}}
userId: 2

{
    "userId": 2,
    "orderItems": [
        {
            "productId": 2,
            "quantity": 4
        },
        {
            "productId": 1,
            "quantity": 3
        }
    ]
}

### Get all subscriptions
GET {{url}}/subscriptions
userId : 2

### create new subscription
POST {{url}}/subscriptions
userId: 2

{
    "productId": 2,
    "quantity": 10,
    "scheduleType": "WEEKLY",
    "deliveryDays": [
    "MONDAY",
    "FRIDAY"
    ]
}

### change subscription status
PATCH {{url}}/subscriptions/1/status
userId: 2

{
    "status": "PAUSED"
}
